import {
 ArrowDownToLine, ArrowLeftRight, ArrowRight, ArrowUpRight, Banknote, BedDouble, Bell, BookOpen, Bookmark, Bus, CalendarClock, CalendarDays, CalendarPlus, Camera, Car, CarTaxiFront, Check, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, Clock3, Cloud, CloudRain, CloudSun, Coffee, Copy, CreditCard, Download, Droplets, Ellipsis, ExternalLink, Eye, FileCheck, FileText, Folder, Footprints, GripVertical, Hash, Heart, House, Image, ImagePlus, Images, Landmark, LayoutGrid, Link, Link2, LogOut, Luggage, MapPin, Menu, MessageCircle, Moon, NotebookPen, Palette, Pencil, Phone, Pin, Plane, PlaneLanding, PlaneTakeoff, Plug, Plus, QrCode, Receipt, Repeat, Search, Send, Share, Share2, Shirt, ShoppingBag, SlidersHorizontal, Smile, Snowflake, Sparkles, SquarePen, Sun, Sunrise, Ticket, TrainFront, Trash, Undo2, UserRound, Users, Utensils, Wallet, X,
} from "lucide-react";

const M = {
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "banknote": Banknote,
  "bed-double": BedDouble,
  "bell": Bell,
  "book-open": BookOpen,
  "bookmark": Bookmark,
  "bus": Bus,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "camera": Camera,
  "car": Car,
  "car-taxi-front": CarTaxiFront,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  "clock-3": Clock3,
  "cloud": Cloud,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  "coffee": Coffee,
  "copy": Copy,
  "credit-card": CreditCard,
  "download": Download,
  "droplets": Droplets,
  "ellipsis": Ellipsis,
  "eye": Eye,
  "file-check": FileCheck,
  "file-text": FileText,
  "folder": Folder,
  "footprints": Footprints,
  "grip-vertical": GripVertical,
  "hash": Hash,
  "heart": Heart,
  "house": House,
  "image": Image,
  "image-plus": ImagePlus,
  "images": Images,
  "landmark": Landmark,
  "layout-grid": LayoutGrid,
  "link": Link,
  "luggage": Luggage,
  "map-pin": MapPin,
  "menu": Menu,
  "message-circle": MessageCircle,
  "moon": Moon,
  "notebook-pen": NotebookPen,
  "palette": Palette,
  "pencil": Pencil,
  "phone": Phone,
  "pin": Pin,
  "plane": Plane,
  "plane-landing": PlaneLanding,
  "plane-takeoff": PlaneTakeoff,
  "plug": Plug,
  "plus": Plus,
  "qr-code": QrCode,
  "receipt": Receipt,
  "repeat": Repeat,
  "search": Search,
  "send": Send,
  "share": Share,
  "share-2": Share2,
  "shirt": Shirt,
  "shopping-bag": ShoppingBag,
  "sliders-horizontal": SlidersHorizontal,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "square-pen": SquarePen,
  "sun": Sun,
  "sunrise": Sunrise,
  "ticket": Ticket,
  "train-front": TrainFront,
  "trash": Trash,
  "user-round": UserRound,
  "users": Users,
  "utensils": Utensils,
  "wallet": Wallet,
  "x": X,
  "log-out": LogOut,
  "undo-2": Undo2,
  "external-link": ExternalLink,
  "calendar-plus": CalendarPlus,
  "link-2": Link2,
  "smile": Smile,
} as const;

export type IcName = keyof typeof M;

/** 목업과 같은 아이콘 (이름은 lucide 그대로) */
export default function Ic({ n, size, className, style }: { n: IcName; size?: number; className?: string; style?: React.CSSProperties }) {
  const C = M[n];
  return <C size={size} className={className} style={style} />;
}
